### ISSUE TITLE
should we just move to eslint?

### ISSUE THREAD

**Issue by mattkrick** [wenzowski/eslint-config-xo-meatier#4]
i think the xo package is kinda going off the deep end: https://github.com/sindresorhus/eslint-plugin-xo/issues/5

Making everything kebab case flies in the face of generally accepted react naming conventions (PascalCase) and JS conventions (camelCase). I'm thinking about ditching it for a good ol `.eslintrc`. Thoughts?

**Comment by wenzowski** [comment]
That's one of the rules I'd like to override here when I merge in the Greenkeeper PRs. I actually like the idea of linting file names, in theory, just not that particular rule.

I've found it helpful to have all project file names equal to the method of their default export plus `.js`. So a file that has `export default class PascalCase` would be named `PascalCase.js` and a file with `export default function camelCase` would be `camelCase.js`.

I'd be much more interested in a meatier linter enforcing something like that by default than snake case or kebab case.

As you point out though, there are established naming conventions. I am in favour of reifying the existing meatier file naming conventions here, rather than imposing an arbitrary new rule.

**Comment by mattkrick** [comment]
yeah, the trick is that file naming conventions depend on what's inside (ie is it a react component or not). I'd love a tool that can detect the default export & check the filename accordingly, but there's no good way to  statically check a stateless functional component, so false positives would always be an issue. Plus, things like helpers & utils that don't have default exports would need default fallback to anything in camelCase.

**Comment by wenzowski** [comment]
yes, exactly.

Any other incompatible new rules need disabling?

**Comment by mattkrick** [comment]
`import-order/import-order`. I've read the eslint page over & over and how it's supposed to work isn't how it works for me. Seems like it still forces me to sort alphabetically THEN by import type. I really like the idea, though. I'll try it again in a couple months after they give it some more love.

**Comment by wenzowski** [comment]
Given that rule is coming in from the deprecated [jfmengels/eslint-plugin-import-order](https://github.com/jfmengels/eslint-plugin-import-order) I totally support turning it off. Tracking replacement in sindresorhus/xo#114

**Comment by jfmengels** [comment]
> Seems like it still forces me to sort alphabetically THEN by import type.

The rule has been moved to [`import/order`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) rule, where it's gotten a bit more configurable.
It does not sort alphabetically (in neither the original or the `import` plugin) though, only by import type. Sorry if it wasn't clear.

In the `import` plugin, you can re-arrange the import type to allow some of them to be mixed, re-arrange the default order, etc. Maybe the alphabetical order sort will come later, but then only as an additional option. You're welcome to open an issue to improve it so that it can better suit your needs :)

**Comment by wenzowski** [comment]
Thanks for that @jfmengels

Merge in of the `import/order` is happening in sindresorhus/xo#109 and I've split tracking of this rule for this project out to #6 with [a skipped test](https://github.com/wenzowski/eslint-config-xo-meatier/commit/d72444d46f3fbefeac4b99810d75c9721f93cbff#diff-c1129c8b045390789fa8ff62f2c6b4a9R40) for when that rule gets enabled.

Any other rule changes @mattkrick or should I tag `0.2.2`?

**Comment by mattkrick** [comment]
those are the only 2 i've noticed (i just edited the meatier `package.json` for a quick exclusion, i'll remove that part on the next version bump).

**Comment by wenzowski** [comment]
ok, tagged `0.2.2` and release will happen automatically
closing
